apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Flower
  description: This app is for Flower Crud operation
spec:
  type: openapi
  lifecycle: experimental
  owner: NC9596
  definition:
    $text: https://github.com/NC9596/FlowerRepoSpring-mvc/blob/master/src/main/resources/api-docs.yaml
