apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Flower"
  description: "This app is for Flower Crud operation"
  annotations:
    github.com/project-slug: NC9596/FlowerRepoSpring-mvc
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - mvc
  links:
    - url: http://localhost:4044/FlowerSpringBootCRUDProj/
      title: Flower Website
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/nc9596"
  providesApis:
    - Flower
#  consumesApis:
#    - petstore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Flower
  description: This app is for Flower Crud operation
spec:
  type: openapi
  lifecycle: experimental
  owner: NC9596
  definition:
    $text: https://github.com/NC9596/FlowerRepoSpring-mvc/blob/master/FlowerSpringCRUDProj/src/main/resources/api-docs.yaml